
const LOGIN_LOAD = "LOGIN_LOAD_CONSTANT";
const LOGIN_DATA = "LOGIN_DATA_CONSTANT";
const LOGIN_ERROR = "LOGIN_ERROR_CONSTANT";
const LOGIN_FAIL = "LOGIN_FAIL_CONSTANT";
const LOGIN_RESET = "LOGIN_RESET_CONSTANT";

