# Generated by Django 4.0.4 on 2022-06-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Имя страны', help_text='<small class="text-muted">Имя страны</small><hr><br>', max_length=254, unique=True, verbose_name='Имя страны:')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Имя города', help_text='<small class="text-muted">Имя страны</small><hr><br>', max_length=254, unique=True, verbose_name='Имя города:')),
                ('country_id', models.ForeignKey(blank=True, db_column='country_db_column', db_tablespace='country_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Из какой страны</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_student.country', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Из какой страны')),
            ],
        ),
    ]
