# Generated by Django 4.0.4 on 2022-05-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='title1',
        ),
    ]
