# Generated by Django 4.0.4 on 2022-05-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0002_rename_title_task_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title1',
            new_name='title',
        ),
    ]
