# Generated by Django 4.0.5 on 2022-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', help_text='<small class="text-muted">это наше сообщение</small><hr><br>', max_length=500, null=True, verbose_name='текст сообщения:')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('text',),
            },
        ),
    ]
