# Generated by Django 4.0.5 on 2022-06-30 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_textmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">время создания</small><hr><br>', null=True, verbose_name='время создания:'),
        ),
    ]
