# Generated by Django 4.0.5 on 2022-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textmodel_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='title',
            field=models.CharField(blank=True, default='', help_text='<small class="text-muted">это наше сообщение</small><hr><br>', max_length=500, null=True, verbose_name='проверка сообщения:'),
        ),
    ]
