# Generated by Django 4.1.2 on 2022-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='<small class="text-muted">это наш заголовок категории истории</small><hr><br>', max_length=250, verbose_name='Заголовок категории истории')),
            ],
            options={
                'verbose_name': 'Категории историй',
                'verbose_name_plural': 'Категории историй',
            },
        ),
    ]
