# Generated by Django 4.1.2 on 2022-12-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_mypost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypost',
            options={'verbose_name': 'посты', 'verbose_name_plural': 'посты'},
        ),
    ]
