# Generated by Django 4.1.2 on 2022-12-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_youtube_video_category_youtube_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtube_video',
            options={'verbose_name': 'видео с ютуба', 'verbose_name_plural': 'Ютуб видео'},
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='category_id',
            field=models.ManyToManyField(blank=True, to='django_app.youtube_video_category', verbose_name='Категория видео'),
        ),
    ]
