# Generated by Django 4.0.6 on 2022-07-21 15:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Название категории', help_text='<small class="text-muted">это наше название</small><hr><br>', max_length=200, unique=True, verbose_name='Название категории:')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории книг',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ModelBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>', max_length=250, null=True, verbose_name='Заголовок:')),
                ('image', models.ImageField(blank=True, default='img/book/avatar/default/default_receipt.jpg', help_text='<small class="text-muted">это наша заставка</small><hr><br>', null=True, upload_to='img/book/avatar', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'bmp', 'jpeg'])], verbose_name='Заставка:')),
                ('time_to_cook', models.IntegerField(blank=True, default='1', help_text='<small class="text-muted">это наше время на приготовление</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Время на приготовление(минуты)')),
                ('description', models.TextField(default='Описание', help_text='<small class="text-muted">это наше Описание</small><hr><br>', verbose_name='Описание:')),
                ('is_completed', models.BooleanField(default=False)),
                ('instructions', models.FileField(blank=True, default=None, help_text='<small class="text-muted">Инструкция</small><hr><br>', null=True, upload_to='file/pdf', validators=[django.core.validators.FileExtensionValidator(['PDF', 'XLSX'])], verbose_name='Инструкция:')),
                ('category', models.ManyToManyField(blank=True, db_column='country_db_column', db_index=True, default=None, error_messages=False, help_text='<small class="text-muted">категория</small><hr><br>', to='backend_api.modelbookcategory', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Категория блюда')),
                ('upload_author', models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('title', 'description'),
            },
        ),
    ]
