# Generated by Django 4.0.6 on 2022-08-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbook',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='country_db_column', db_index=True, default=None, error_messages=False, help_text='<small class="text-muted">категория</small><hr><br>', to='backend_api.modelbookcategory', verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='modelbook',
            name='upload_author',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
    ]
