# Generated by Django 4.0.6 on 2022-08-02 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_modelbook_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbook',
            name='image',
            field=models.ImageField(blank=True, default='default/modelbooks/default_book.jpg', help_text='<small class="text-muted">это наша заставка</small><hr><br>', null=True, upload_to='img/book/avatar', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'bmp', 'jpeg'])], verbose_name='Заставка:'),
        ),
    ]
