# Generated by Django 4.0.6 on 2022-08-04 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_modelbook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelbook',
            name='image',
            field=models.ImageField(blank=True, default='default/modelbooks/default_book.jpg', help_text='<small class="text-muted">это наша заставка</small><hr><br>', null=True, upload_to='modelbooks/avatar', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Заставка:'),
        ),
        migrations.AlterField(
            model_name='modelbook',
            name='instructions',
            field=models.FileField(blank=True, default=None, help_text='<small class="text-muted">Инструкция</small><hr><br>', null=True, upload_to='modelbooks/file', validators=[django.core.validators.FileExtensionValidator(['PDF'])], verbose_name='Инструкция:'),
        ),
    ]
