# Generated by Django 4.0.6 on 2022-08-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_modelbook_image_alter_modelbook_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbookcategory',
            name='description',
            field=models.TextField(default='Описание', help_text='<small class="text-muted">это наше Описание</small><hr><br>', verbose_name='Описание:'),
        ),
    ]
