# Generated by Django 4.0.6 on 2022-08-05 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_api', '0006_modelbookcategory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelbookcategory',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='modelbook',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='modelbook',
            name='time_to_cook',
        ),
        migrations.AddField(
            model_name='modelbook',
            name='is_view',
            field=models.BooleanField(blank=True, default=False, help_text='<small class="text-muted"></small><hr><br>', verbose_name='Видимость книги в общем доступе:'),
        ),
        migrations.AddField(
            model_name='modelbook',
            name='time_to_read',
            field=models.IntegerField(blank=True, default='1', help_text='<small class="text-muted"></small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Время на чтение'),
        ),
        migrations.AlterField(
            model_name='modelbook',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, default=None, error_messages=False, help_text='<small class="text-muted"></small><hr><br>', to='backend_api.modelbookcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='modelbook',
            name='title',
            field=models.CharField(blank=True, default='Заголовок', help_text='<small class="text-muted"></small><hr><br>', max_length=250, null=True, unique=True, verbose_name='Заголовок:'),
        ),
        migrations.AlterField(
            model_name='modelbook',
            name='upload_author',
            field=models.ForeignKey(blank=True, default=None, help_text='<small class="text-muted"></small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор загрузил'),
        ),
        migrations.AlterField(
            model_name='modelbookcategory',
            name='description',
            field=models.TextField(default='Описание', help_text='<small class="text-muted"></small><hr><br>', verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='modelbookcategory',
            name='title',
            field=models.CharField(blank=True, default='Название категории', help_text='<small class="text-muted"></small><hr><br>', max_length=200, unique=True, verbose_name='Название категории:'),
        ),
    ]
