# Generated by Django 4.0.6 on 2022-08-25 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_modelbookcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelbook',
            name='created_datetime_field',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">datetime_field</small><hr><br>', null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='modelbook',
            name='update_datetime_field',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='<small class="text-muted">datetime_field</small><hr><br>', null=True, verbose_name='Дата и время обновления'),
        ),
    ]
