# Generated by Django 4.0.4 on 2022-05-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='заголовок', help_text='<small class="text-muted">это наш заголовок</small><hr><br>`', max_length=254, null=True, verbose_name='Заголовок:'),
        ),
    ]
