export const CONST_NEWS_BOOKS_LOAD = "CONST_NEWS_BOOKS_LOAD";
export const CONST_NEWS_BOOKS_DATA = "CONST_NEWS_BOOKS_DATA";
export const CONST_NEWS_BOOKS_ERROR = "CONST_NEWS_BOOKS_ERROR";
export const CONST_NEWS_BOOKS_FAIL = "CONST_NEWS_BOOKS_FAIL";
export const CONST_NEWS_BOOKS_RESET = "CONST_NEWS_BOOKS_RESET";


