# Generated by Django 4.0.4 on 2022-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0002_receiptcategory_alter_receipt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, default='Описание', help_text='<small class="text-muted">это наше Описание</small><hr><br>', null=True, verbose_name='Описание:'),
        ),
    ]
