# Generated by Django 4.0.4 on 2022-06-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0003_alter_receipt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(default='Описание', help_text='<small class="text-muted">это наше Описание</small><hr><br>', verbose_name='Описание:'),
        ),
    ]
