# Generated by Django 4.0.4 on 2022-06-04 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teacher', '0005_receiptrating_receiptcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptcomment',
            options={'ordering': ('receipt',), 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AlterModelOptions(
            name='receiptrating',
            options={'ordering': ('receipt',), 'verbose_name': 'Рейтинг рецепта', 'verbose_name_plural': 'Рейтинги рецептов'},
        ),
        migrations.RemoveField(
            model_name='receiptcomment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='receiptrating',
            name='title',
        ),
        migrations.AddField(
            model_name='receiptcomment',
            name='comment_text',
            field=models.CharField(blank=True, default='Текст комментария', help_text='<small class="text-muted">Текст комментария</small><hr><br>', max_length=500, null=True, verbose_name='Заголовок:'),
        ),
        migrations.AddField(
            model_name='receiptcomment',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Пользователь</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='receiptrating',
            name='rating_value',
            field=models.IntegerField(blank=True, default='0', help_text='<small class="text-muted">Оценка</small><hr><br>', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='receiptrating',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Пользователь</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='receiptcomment',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='receiptrating',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
    ]
