# Generated by Django 4.0.4 on 2022-06-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0007_receipt_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='Название', help_text='<small class="text-muted">это наше название</small><hr><br>', null=True, verbose_name='Название:')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории рецептов',
                'ordering': ('name',),
            },
        ),
    ]
