# Generated by Django 4.0.4 on 2022-06-07 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teacher', '0011_remove_receipt_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptcomment',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='receiptrating',
            name='user',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Пользователь</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Пользователь'),
        ),
    ]
