# Generated by Django 4.0.4 on 2022-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0012_alter_receiptcomment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=None, help_text='<small class="text-muted">ингредиенты</small><hr><br>', to='app_teacher.receiptingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
