# Generated by Django 4.0.4 on 2022-06-07 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teacher', '0013_receipt_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор блюда'),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='country_db_column', db_index=True, db_tablespace='country_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">категория</small><hr><br>', to='app_teacher.receiptcategory', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Категория блюда'),
        ),
    ]
