# Generated by Django 4.0.4 on 2022-06-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_teacher', '0014_alter_receipt_author_remove_receipt_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">автор</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Автор блюда'),
        ),
    ]
