# Generated by Django 4.0.4 on 2022-06-10 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0015_alter_receipt_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='instructions',
            field=models.FileField(blank=True, default=None, help_text='<small class="text-muted">Инструкция</small><hr><br>', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'word'])], verbose_name='Инструкция:'),
        ),
    ]
