# Generated by Django 4.0.4 on 2022-06-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0020_alter_receipt_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcomment',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='<small class="text-muted">время создания</small><hr><br>', null=True, verbose_name='время создания:'),
        ),
        migrations.AlterField(
            model_name='receiptrating',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
    ]
