# Generated by Django 4.0.4 on 2022-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0022_receiptcomment_create_receiptcomment_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptcomment',
            options={'ordering': ('-time',), 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AddField(
            model_name='receiptrating',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False, help_text='<small class="text-muted">Лайк</small><hr><br>', null=True, verbose_name='Лайк:'),
        ),
    ]
